### ISSUE TITLE
Problem in mesh extraction

### ISSUE THREAD

**Issue by hritam-98** [Ysz2022/Fourier123#5]
While running the following code:

`python convert.py big --test_path ./workspace_test/backpack `

I am facing the following issue:

`Traceback (most recent call last):
  File "/local/home/work/fourier123/Fourier123/convert.py", line 19, in <module>
    from kiui.mesh_utils import clean_mesh, decimate_mesh
  File "/home/miniconda3/envs/fourier123/lib/python3.10/site-packages/kiui/mesh_utils.py", line 6, in <module>
    import pymeshlab as pml
  File "/home/miniconda3/envs/fourier123/lib/python3.10/site-packages/pymeshlab/__init__.py", line 11, in <module>
    from .pmeshlab import *
ImportError: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /home/miniconda3/envs/fourier123/lib/python3.10/site-packages/pymeshlab/lib/libpython3.10.so.1.0)`

any idea how to fix this? I assume this is because of the GNU version of linux?

**Comment by Ysz2022** [comment]
Run
`sudo vi /etc/apt/sources.list`

`deb http://th.archive.ubuntu.com/ubuntu jammy main`

`sudo apt update `
`sudo apt install libc6`

Hope this can work well.

**Comment by hritam-98** [comment]
Thank you for the update. Can you please explain the evaluation dataset details? Which subset of Omniobject and GSO did you select? How did you download and use the data? A clear guideline for inference would be helpful

**Comment by Ysz2022** [comment]
You can find the Omniobject here: https://openxlab.org.cn/datasets/OpenXDLab/OmniObject3D-New/tree/main

You can find the GSO here: https://app.gazebosim.org/GoogleResearch

The evaluation details have been displayed in Sec. 5.1 of the paper. The data we have adopted is still in use and the exact details will be open-sourced gradually in the future.

**Comment by Ysz2022** [comment]
You can find the Omniobject here: https://omniobject3d.github.io/

You can find the GSO here: https://app.gazebosim.org/GoogleResearch

The evaluation details have been displayed in Sec. 5.1 of the paper. The data we have adopted is still in use and the exact details will be open-sourced gradually in the future.

**Comment by Ysz2022** [comment]
You can find the Omniobject here: https://openxlab.org.cn/datasets/OpenXDLab/OmniObject3D-New/explore/main

You can find the GSO here: https://app.gazebosim.org/GoogleResearch

The evaluation details have been displayed in Sec. 5.1 of the paper. The data we have adopted is still in use and the exact details will be open-sourced gradually in the future.

**Comment by Ysz2022** [comment]
I will temporarily close this issue and you are free to reopen it once you have any further questions.
